import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getSchool } from "@/lib/schools";

export const dynamicParams = true;

export default async function SchoolPage({ params }: { params: Promise<{ slug: string }> }) {
  const school = getSchool((await params).slug);
  if (!school) notFound();
  return <main><header className="site-header"><Link className="brand" href="/"><span>Top</span> Edu</Link><nav><Link href="/#director">Școli</Link><Link href="/metodologie">Metodologie</Link><Link href="/recenzii">Recenzii</Link></nav><a className="header-action" href="/#director">Caută o școală</a></header><section className="profile-hero"><div className="profile-photo"><Image src={school.image} alt="Ilustrație pentru unitatea de învățământ" fill priority sizes="(max-width: 900px) 100vw, 48vw" /></div><div className="profile-intro"><Link className="back-link" href="/#director">← Înapoi la școli</Link><p className="kicker">{school.type}</p><h1>{school.name}</h1><p className="profile-location">📍 {school.city} · {school.county}</p><span className="demo-badge">Sursă: Ministerul Educației · 2025–2026</span></div></section><div className="profile-stats"><div><strong>Rețea oficială</strong><span>unitate verificată</span></div><div><strong>{school.levels}</strong><span>niveluri de studiu</span></div><div><strong>{school.ownership}</strong><span>tip de proprietate</span></div></div><div className="profile-tabs"><span>Despre școală</span><span>Date oficiale</span><span>Date în pregătire</span></div><section className="profile-layout"><article><div className="content-card"><p className="kicker">Despre școală</p><h2>O imagine clară, din surse publice</h2><p>{school.description}</p></div><div className="content-card"><p className="kicker">Date în pregătire</p><h2>Adăugăm informații utile</h2><p>Lucrăm la date financiare, contact public și eligibilitatea pentru 3,5%. Publicăm numai informații cu sursă verificabilă.</p></div></article><aside className="facts-card"><h2>Date oficiale</h2><dl><div><dt>Niveluri</dt><dd>{school.levels}</dd></div><div><dt>Proprietate</dt><dd>{school.ownership}</dd></div><div><dt>Localitate</dt><dd>{school.city}</dd></div><div><dt>Județ</dt><dd>{school.county}</dd></div><div><dt>Adresă</dt><dd>{school.address || "Nu este publicată"}</dd></div><div><dt>Cod SIIIR</dt><dd>{school.siiirCode}</dd></div><div><dt>Sursa</dt><dd>{school.source}</dd></div></dl></aside></section></main>;
}
