import Image from "next/image";
import Link from "next/link";
export type ProfileVariantKind = "gradinita" | "scoala-gimnaziala" | "clubul-copiilor" | "centru-suport";
const profiles = {
  gradinita:{type:"Grădiniță",title:"Un început bun, în fiecare zi.",place:"Grădinița Curcubeul · Brașov",image:"/top-edu-family.png",stats:[["96","copii"],["5","grupe"],["program","normal + prelungit"]],sections:[["Program și grupe","Grupe mici, mijlocii și mari · 08:00–18:00","Masă caldă și program prelungit — în pregătire"],["Activități","Joc, mișcare, muzică și explorare în aer liber.","Detaliile programului sunt publicate de unitate."],["Contact","Adresă, telefon și website oficial","În pregătire"]]},
  "scoala-gimnaziala":{type:"Școală gimnazială",title:"Un loc bun pentru a crește curios.",place:"Școala Gimnazială Nr. 5 · Cluj-Napoca",image:"/school-cluj.png",stats:[["642","elevi"],["28","clase"],["48","cadre didactice"]],sections:[["Despre școală","Comunitate gimnazială cu proiecte, cluburi și spații pentru învățare activă.","Sursă: Ministerul Educației"],["Evaluarea Națională","Medie și rată de promovare","Datele pe unitate pentru 2024–2025 sunt în pregătire"],["Facilități și activități","Bibliotecă, laborator, sport și cluburi după școală.","Actualizat: 2025–2026"]]},
  "clubul-copiilor":{type:"Clubul Copiilor",title:"Descoperă ce îți place.",place:"Clubul Copiilor · Iași",image:"/school-iasi.png",stats:[["12","cercuri"],["6–18","ani"],["gratuit","înscriere"]],sections:[["Cercuri și activități","Arte, robotică, sport, teatru și muzică — fiecare copil își găsește locul.","Programul complet: în pregătire"],["Înscriere","Participarea este gratuită, în limita locurilor disponibile.","Contact direct cu instituția"],["Rezultate","Participări la concursuri și proiecte locale.","Sursa: instituția"]]},
  "centru-suport":{type:"Centru de suport educațional",title:"Sprijin pentru școli și oameni.",place:"CJRAE Brașov · Brașov",image:"/school-bucharest.png",stats:[["13","localități"],["5","servicii"],["oficial","rețea publică"]],sections:[["Servicii","Consiliere, orientare școlară, sprijin psihopedagogic și formare.","Aria de acoperire: județul Brașov"],["Documente publice","Metodologii, rapoarte și formulare utile pentru familii și școli.","Linkurile sunt în pregătire"],["Contact","Adresă, email și program cu publicul.","Sursă: instituția"]]}
} as const;
export function ProfileVariant({kind}:{kind:ProfileVariantKind}){const p=profiles[kind];return <main className="variant-page"><header className="site-header"><Link className="brand" href="/"><span>Top</span> Edu</Link><nav><Link href="/#director">Școli</Link><Link href="/metodologie">Metodologie</Link><Link href="/recenzii">Recenzii</Link></nav><Link className="header-action" href="/#director">Explorează datele →</Link></header><section className="variant-hero"><div className="variant-photo"><Image src={p.image} alt="Comunitate educațională din România" fill priority sizes="(max-width: 800px) 100vw, 52vw" /></div><div className="variant-intro"><Link className="back-link" href="/#director">← Înapoi la școli</Link><p className="kicker">{p.type}</p><h1>{p.title}</h1><p className="profile-location">📍 {p.place}</p><span className="demo-badge">Sursă publică verificată · 2025–2026</span></div></section><section className="variant-stats">{p.stats.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><div className="variant-tabs"><span>Prezentare</span><span>Date oficiale</span><span>Contact și surse</span></div><section className="variant-grid"><div>{p.sections.map(([title,body,note])=><article className="variant-card" key={title}><p className="kicker">{title}</p><h2>{body}</h2><p>{note}</p></article>)}</div><aside className="facts-card"><h2>Date despre unitate</h2><dl><div><dt>Tip</dt><dd>{p.type}</dd></div><div><dt>Localitate</dt><dd>{p.place}</dd></div><div><dt>Actualizare</dt><dd>2025–2026</dd></div><div><dt>Website oficial</dt><dd>În pregătire</dd></div><div><dt>Contact public</dt><dd>În pregătire</dd></div></dl></aside></section><footer className="variant-footer"><span>Top Edu · date publice, pe înțelesul tuturor.</span><Link href="/metodologie">Cum lucrăm →</Link></footer></main>}
